/**:
  ros__parameters:
    general:
      camera_model: zedxm
      serial_number: 53927609
      camera_name: "mercury/ffc"
      pub_resolution: "NATIVE" # The resolution used for image and depth map publishing. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
      # pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
      pub_frame_rate: 30.0
      # optional_opencv_calibration_file: "/home/ros/zed_cals/zedxmffc_calibration.yaml"
      grab_resolution: 'HD1200'
      self_calib: false
    pos_tracking:
      pos_tracking_enabled: true
      pos_tracking_mode: "GEN_3"
      imu_fusion: true
      publish_tf: false
      publish_map_tf: false
      odometry_frame: 'odom'
      area_memory: false
      reset_odom_with_loop_closure: false
      set_gravity_as_origin: true
      floor_alignment: false
      two_d_mode: false
      publish_odom_pose: true
      publish_pose_covariance: true
    video:
      publish_rgb: false
      publish_left_right: true
      publish_stereo: false
      publish_raw: false      # only if you also want raw topics
      publish_gray: true   # apriltag depends on me
    debug:
      debug_common: false
      debug_point_cloud: false
      debug_video_depth: false